environment : PROD

logging.file.name: application.log
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: ERROR
    com.bridgelabz: DEBUG

logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{5}:%lineJ %msg%n'

logging.pattern.console:
spring.main.banner-mode: off