spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_payroll?createDatabaseIfNotExist=true
    username: root
    password: Abhi

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file.name: application.log
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: ERROR
    com.bridgelabz: DEBUG

  pattern.console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{5}:%lineJ %msg%n'
