spring.profiles.active: DEV
environment: COMMON

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PAYROLL_DB?createDatabaseIfNotExist=true
    username: ${PAYROLL_DB_USERNAME:payrolluser}
    password: ${PAYROLL_DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
